### PR TITLE
Add support for unix timestamps.

### PR DESCRIPTION
**Pull request by SiliconValet**

### CODE REVIEW

**Comment by mwcz** [comment]
Tests please. :)

**Comment by SiliconValet** [comment]
ah, good call. I can add that.

**Comment by SiliconValet** [comment]
I've written some tests locally, but can't get the tests to kick off. I get "chrome failed to maximize" and hard hang. I'll investigate later today.

**Comment by SiliconValet** [comment]
Added test, but I can't run them on my setup. /shrug

**Comment by SiliconValet** [comment]
Ok tests fixed and validated. ready for review.

**Pull request merged**
