### PR TITLE
Rh icon update

### PR DESCRIPTION
**Pull request by markcaron**
Add ALL the icons!

### CODE REVIEW

**Comment by kylebuch8** [comment]
I think the resulting rh-icon.compiled.js file is too big. It's coming in at 594 KB. I think we should look at breaking this down into sets of icons that we deliver. What do you think?

**Comment by markcaron** [comment]
Agreed. Let's discuss how to properly break it up.

**Comment by mwcz** [comment]
Should we close this PR?

**Comment by mwcz** [comment]
Closing for now.

**Pull request closed without merging**
