### PR TITLE
Added comments to theme files

### PR DESCRIPTION
**Pull request by starryeyez024**

### CODE REVIEW

**Comment by kylebuch8** [comment]
@starryeyez024 Do we really want to add these comments into master?

**Comment by mwcz** [comment]
I think a meeting to discuss these comments would be great, but not merging them into master.

**Comment by mwcz** [comment]
@starryeyez024 sorry, @castastrophe told me that you guys regularly open MRs to allow line-by-line discussion, without intending to merge the comments.  I'd never heard of doing that before but it seems pretty clever!

**Comment by mwcz** [comment]
Is this still under review?

**Comment by starryeyez024** [comment]
@mwcz the comments tactic was per @mcaron request, Mark did you have a chance to look?

**Comment by markcaron** [comment]
@starryeyez024, Reviewing now.

**Comment by kylebuch8** [comment]
@starryeyez024 Can we close this?

**Pull request closed without merging**
